In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.externals import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression

C:\Users\Ben\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


## Load data

In [2]:
# Importing the dataset
missing_values = ["n/a", "na", "--"]
dataset = pd.read_csv('final_df2.csv', na_values = missing_values)

In [3]:
print(dataset.isnull().sum())

Tm             0
#Bat           0
#Fld           0
#P             0
2B             0
3B             0
A              0
AB             0
BA             0
BB9            0
BB_x           0
BB_y           0
BF             0
BK             0
BatAge         0
CG_x           0
CG_y           0
CS             0
Ch             0
DP             0
DefEff         0
E              0
ER             0
ERA            0
ERA+           0
FIP            0
Fld%           0
G              0
GDP            0
GF             0
            ... 
PA             0
PAge           0
PO             0
R/G            0
RA/G_x         0
RA/G_y         0
RBI            0
R_x            0
R_y            0
Rdrs         870
Rdrs/yr      870
Rtot           0
Rtot/yr        0
SB             0
SF             0
SH             0
SLG            0
SO/W           0
SO9            0
SO_x           0
SO_y           0
SV             0
TB             0
W              0
W-L%           0
WHIP           0
WP             0
cSho          

In [4]:
del dataset['Rdrs']
del dataset['Rdrs/yr']


In [5]:
del dataset ['Tm']

In [6]:
dataset.head()

#Bat  #Fld  #P   2B  3B     A    AB     BA  BB9  BB_x  ...  SO_y  SV    TB  \
0    39    39  18  195  22  1635  5460  0.258  2.7   438  ...   665  42  2073   
1    30    30  14  234  29  1729  5518  0.265  3.0   498  ...   806  36  2282   
2    40    40  19  234  37  1778  5494  0.251  4.2   685  ...   923  41  2280   
3    45    45  19  151  29  1756  5316  0.230  3.2   517  ...   929  39  1694   
4    41    39  17  215  40  1868  5530  0.253  2.9   475  ...   928  27  2121   

     W   W-L%   WHIP  WP  cSho  tSho  WS Winner  
0   93  0.574  1.226  40     7     7          0  
1  109  0.673  1.148  34    19    20          0  
2   87  0.537  1.437  61     4     7          0  
3   71  0.438  1.259  64     6     9          0  
4   92  0.568  1.266  39    18    22          0  

[5 rows x 79 columns]

In [7]:
test2019 = pd.read_excel('df2019.xlsx')
teams = test2019['Tm']

In [8]:
del test2019['Tm']

In [9]:
test2019 = test2019.iloc[:,:]

# Generate Synthetic Samples

In [10]:

from imblearn.over_sampling import SMOTE

# Separate input features and target
y = dataset['WS Winner']
X = dataset.drop('WS Winner', axis=1)

# setting up testing and training sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=27)

sm = SMOTE(random_state=27, ratio=1.0)
X_train, y_train = sm.fit_sample(X_train, y_train)

Using TensorFlow backend.


In [12]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, recall_score

smote = LogisticRegression(solver='liblinear').fit(X_train, y_train)

smote_pred = smote.predict(X_test)

# Checking accuracy
accuracy_score(y_test, smote_pred)

0.8461538461538461

In [13]:
smote_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
# concatenate our training data back together
X = pd.concat([X_train, y_train], axis=1)
X.head()

# Kernal SVM Classification

In [14]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
SVCclassifier = SVC(kernel = 'rbf', probability=True, random_state = 0)
SVCclassifier.fit(X_train, y_train)

C:\Users\Ben\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=True, random_state=0, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
help(SVC)

In [15]:
y_pred = SVCclassifier.predict(X_test)

In [16]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [17]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[324,   0],
       [ 14,   0]], dtype=int64)

This project could be modified into a regression model by including all teams in the playoffs, ranking them ordinally on how far they got, and them making this a new column